Add zh_cn translation for quote subtitles
Extegral/Enigmatic-Legacy pull request #418
Opened 2023-04-11 04:47 UTC by Water-Moon

I tried my best but I'm not sure if it persisted the emotions and feelings of the original text well enough

2023-07-28 14:05 UTC, TUsama requested changes
先看这一部分，后面的之后再说。

2023-07-28 14:05 UTC, TUsama commented on src/main/resources/assets/enigmaticlegacy/lang/zh_cn.json
> -  "quote.with_dragons_3": "...or return to the facade of sanity and liveliness the Overworld provides?",
facade 意在指明主世界提供的 sanity and liveliness 的表面性与虚假性，此处译文中并未体现出来。

2023-07-28 14:05 UTC, TUsama commented on src/main/resources/assets/enigmaticlegacy/lang/zh_cn.json
> +  "quote.end_doorstep_1": "终末之地的门户已经打开…只差迈出最后一步了。",
尽量用全部的省略号，否则有可能会出现无法预料的外观问题。

2023-07-28 14:05 UTC, TUsama commented on src/main/resources/assets/enigmaticlegacy/lang/zh_cn.json
> +  "quote.we_fall_1": "我们之所以跌倒，是为了学习如何重新站起来。",
此处与原文有着微妙的逻辑差异，但此翻译也不是不行，就是略有一些矫情。

2023-07-28 14:05 UTC, TUsama commented on src/main/resources/assets/enigmaticlegacy/lang/zh_cn.json
> +  "quote.oblivion_rejects_1": "深渊拒绝了你…在你还活着的时候，好好利用这次机会吧。",
~~此处触发条件是什么？这里的“深渊拒绝了你”，是指的玩家复活？没有陷入永久的死亡？~~
首先不是深渊，而是湮灭，湮灭基石中的湮灭
看了一下源码，确实是死亡触发。那么这里的意思就是，术石劝解玩家，既然湮灭拒绝了你，那么你要好好利用此次机会，不要浪费了。
```suggestion
  "quote.oblivion_rejects_1": "湮灭拒绝了你……毕竟你是不死的，在你尚未失去不死之身前，好好利用这一归来的机会吧。",

```
while you still can “表示应该在某个时候或某个机会还存在的时候抓住它，因为它可能不会持续太久”，此处需要将暗示的内容具体化出来。
这里涉及到一点背景，非欧立方知道玩家是不死的、不朽的半神，所以这里才会这样说。

2023-07-28 14:05 UTC, TUsama commented on src/main/resources/assets/enigmaticlegacy/lang/zh_cn.json
> +  "quote.eternity_to_keep_1": "不惜一切代价去尝试吧——你还有无数次机会。",
原文的 eternity 是必须译为“不死”“不朽”“永生”的，以于常规生物的“可死”“可朽”“短生”区分开来。

2023-07-28 14:05 UTC, TUsama commented on src/main/resources/assets/enigmaticlegacy/lang/zh_cn.json
> +  "quote.violence_calls_1": "当你被这世界残酷对待时，你默默积攒着复仇的怒火。回去，释放这份怒火！",
```suggestion
  "quote.violence_calls_1": "暴力，吹响了复仇号角的第一声。回去，让你那复仇的怒火烧尽一切！",
```
句意与原文仍有差距，此处提供另一种文学化的修改意见。除却前面一句，后面的“dispense”也没有把握住，原译文把握住了dispense的动作，但是并未把握到其根据上下文产生的神髓。

2023-07-28 14:05 UTC, TUsama commented on src/main/resources/assets/enigmaticlegacy/lang/zh_cn.json
> +  "quote.immortal_1": "你是不朽的！回去给造成这一切的生物一个教训吧。",
```suggestion
  "quote.immortal_1": "你，乃不朽！归来吧，让那些卑微的生物在你的不朽之姿下颤抖吧！",

```
原译神髓具无，此处提供一个略显浮夸的方案。

2023-07-28 14:05 UTC, TUsama commented on src/main/resources/assets/enigmaticlegacy/lang/zh_cn.json
> +  "quote.its_destruction_1": "能够杀死如此可怖的存在，无疑是不幸中的万幸…",
a small consolation 怎么就译为了“不幸中的万幸”？
而且此句是摧毁七咒之戒时触发，“杀死”明显不对。

2023-07-28 14:05 UTC, TUsama commented on src/main/resources/assets/enigmaticlegacy/lang/zh_cn.json
> +  "quote.i_wandered_1": "我曾经无数次游历过这片大地…",
```suggestion
  "quote.i_wandered_1": "没错，我曾多次在这些破碎的陆地上游荡……",

```
此处是你踩进末地传送门的时候的触发句子。考虑到“大地”这个词在中文中总是暗示着一片完整的大陆，所以改成了“这些破碎的陆地”。
还有“无数次”实在是有点过于发挥了。

2023-08-03 10:56 UTC, Aizistral commented
@TUsama, as I see you've gone through the effort of reviewing this PR quite thoroughly. Since you don't know Chinese, could you provide a general overview of your conclusions in English? I'd like to understand whether it would be reasonable to merge this as-is.

2023-08-03 11:18 UTC, TUsama commented
in general, there are still some translations that are inaccurate and misleading. But considering it is just volunteer work so that's not bad.  if you want to merge it rn, then go on, I may send a PR for the polishing and you can merge that in your next update, I don't want to disturb your schedule.

2023-08-03 11:26 UTC, Aizistral commented
Alright then! 👍 I will indeed merge this now, and if anything - I'll be happy to accept your PR with corrections.

2023-08-03 11:27 UTC, merged